refactor: Replace a bunch of global vars with macro
EttyKitty/ChapterMaster pull request #151
Opened 2024-11-20 12:36 UTC by EttyKitty

I'm not 100% why, but you can't reference a macro directly, i.e. `array_length(macro)` fails on build. Because of that, I had to assign macro into local vars beforehand.

I just want to generally note: globals that are used as constants are a bad practice. Very bad.
![image](https://github.com/user-attachments/assets/820ccf97-52ba-47d9-9d8a-cc76e5d654e6)

### Todo:

- [x] ~~I want to see if it's possible to replace global static structs with something. Macro can't hold structs, so it should be something else.~~ You can use a function, that'll return a struct, but this is no better in terms of reference overhead and additionally creates struct to be garbage collected on every call. So, no, there is no better way, I don' think.
- [x] ~~Figure out if using static variables is actually worse for performance than locals.~~ They are.  Unless you want a variable to preform like a persistent instance variable of a function, that you can modify and reference throughout your code, kinda like a global var, you shouldn't use static vars. They take up memory and are never freed, the same way as globals. 
Honestly, I'm not even sure how are they different from globals. Maybe only in how you reference them, with `function_name.static_name`.

2024-11-21 00:54 UTC, OH296 approved these changes

2024-11-21 00:55 UTC, OH296 requested changes
Can we come up with some sort of standardised syntax for macro names, imo it would remove chances for confusion?

2024-11-21 01:35 UTC, EttyKitty commented
> Can we come up with some sort of standardised syntax for macro names, imo it would remove chances for confusion?

Oh, my bad. I actually forgot about it.
We already have some, not sure what prefixes to use here tho.
![image](https://github.com/user-attachments/assets/aac318fa-3cb6-4378-a4fb-352f721e0d0a)

2024-11-22 20:32 UTC, OH296 commented
> > Can we come up with some sort of standardised syntax for macro names, imo it would remove chances for confusion?
> 
> Oh, my bad. I actually forgot about it. We already have some, not sure what prefixes to use here tho. ![image](https://private-user-images.githubusercontent.com/20323032/388320490-aac318fa-3cb6-4378-a4fb-352f721e0d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDc3NjMsIm5iZiI6MTczMjMwNzQ2MywicGF0aCI6Ii8yMDMyMzAzMi8zODgzMjA0OTAtYWFjMzE4ZmEtM2NiNi00Mzc4LWE0ZmItMzUyZjcyMWUwZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIwMzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTdkNjRlZjRiZTdmZDlkYjQ5ZGI2MDM2ZmY5NzBiOGUwM2M4MDhkY2MyMGM5YzAzNjgyYjJlYjRmMmU3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ohvSEtDa-v-gCBCNwE6Zp1W4vAMmnPNKJeu79xF5UUc) Maybe a better idea to just use all CAPS for them. I guess we can start naming them by what data type they are holding. I.e. ARR_body_parts, STR_date_time, etc.

forgot that this was probably on hold waiting for me to reply. I have no problem using the example approach

2024-11-25 18:38 UTC, merged