refactor: Combat Loss Arrays to Prevent Bounds Issues
EttyKitty/ChapterMaster pull request #20
Opened 2024-10-19 07:30 UTC by jhillacre

This pull request refactors the handling of `lost` and `lost_num` arrays in `obj_pnunit` to address potential bounds issues from hard-coded iterations. The updates ensure dynamic array sizing and consistent zero-indexed operations, improving stability.

- Switched to dynamic arrays to handle varying numbers of lost units safely.
- Standardized array iteration to prevent out-of-bounds errors.
- Optimized target selection by using only valid targets, enhancing performance.
- Simplified scripts and added documentation for better maintainability.

2024-10-19 08:00 UTC, jhillacre commented
The scr_clean function is designed for handling player casualties, with logic and comments clearly aimed at processing damage to player units. However, it gets called with enemy unit objects in scr_shoot, causing errors since it wasn't built to handle enemy casualties.

I'll see if I can fix it or just bandaid it when I look at it tomorrow.

2024-10-20 06:41 UTC, jhillacre commented
- Refactored `scr_clean` to receive target data as arguments rather than setting them on target_object.
- Updated `scr_shoot` and related scripts to align with this approach.

2024-10-20 10:42 UTC, OH296 requested changes
noticed a few things to add

2024-10-20 10:42 UTC, OH296 commented on scripts/scr_flavor2/scr_flavor2.gml
> +                        obj_ncombat.dead_jim[obj_ncombat.dead_jims] = $"{obj_ini.TTRPG[marine_co[him]][marine_id[him]].name_role()} has been critically injured!";
```suggestion
                        obj_ncombat.dead_jim[obj_ncombat.dead_jims] = $"{unit_struct[him].name_role()} has been critically injured!";
```

2024-10-20 10:42 UTC, OH296 commented on scripts/scr_powers/scr_powers.gml
> +            if (unit.IsSpecialist("dreadnoughts")) {
```suggestion
            var armour_data = unit.armour_data();
            var is_dread = false;
            if (is_struct(armour_data)){
                 is_dread = armour_data.has_tag("dreadnought);
            }
            if (is_dread) {
```
This will be more adaptable moving forward, but worth adding a //TODO to incorporate logic into IsSpecialist method

2024-10-20 10:42 UTC, OH296 commented on scripts/scr_shoot/scr_shoot.gml
>  				if (wep_owner[weapon_index_position] != "assorted") then target_object.hostile_shooters = 1;
```suggestion
				if (wep_owner[weapon_index_position] == "assorted"){ target_object.hostile_shooters = 999;}
				else if (wep_owner[weapon_index_position] != "assorted"){ target_object.hostile_shooters = 1;}
```

optomise with else if statement

2024-10-20 10:45 UTC, OH296 commented on objects/obj_pnunit/Create_0.gml
> +// Hardcoded lengths lead to bounds issues when hardcoded values disagree.
any idea how many hardcoded values does this leave remaining? I managed to remove most of the base unit data ones, combined with this thats a large amount of the infrastructure of combat rewritten. I wander we shouldn't work on some batch testing methods for combat before this and my previous rework goes live in a release?

2024-10-20 10:46 UTC, OH296 commented on objects/obj_pnunit/Step_0.gml
>  diff=0;pos=880;siz=min(400,(men*0.5)+(veh*2.5)+(dreads*2));
```suggestion
var diff=0;
var pos=880;
var siz=min(400,(men*0.5)+(veh*2.5)+(dreads*2));
```

2024-10-20 10:47 UTC, OH296 commented on scripts/scr_clean/scr_clean.gml
> +                var random_index = irandom(array_length(valid_vehicles) - 1);
```suggestion
                var random_index = array_random(valid_vehicles);
```
i've made up a few functions to simplify things like this

2024-10-20 10:52 UTC, OH296 commented on scripts/scr_player_combat_weapon_stacks/scr_player_combat_weapon_stacks.gml
> +                var is_dreadnought = unit.armour()=="Dreadnought";
```suggestion
            var armour_data = unit.armour_data();
            var is_dreadnought = false;
            if (is_struct(armour_data)){
                 is_dreadnought = armour_data.has_tag("dreadnought);
            }
```
more adaptable in case we bring in variant items

2024-10-20 10:53 UTC, OH296 commented on scripts/scr_powers/scr_powers.gml
> +        if (unit.hp() < 0){
```suggestion
        if (unit.hp() < 0){//TODO create is_dead function to remove repeats of this log
```

2024-10-20 10:54 UTC, OH296 requested changes
noticed a few further things made as suggestions so shouldn't be any burden

2024-10-20 14:21 UTC, jhillacre commented on objects/obj_pnunit/Create_0.gml
> +// Hardcoded lengths lead to bounds issues when hardcoded values disagree.
> any idea how many hard-coded values does this leave remaining?

I'd suspect anywhere there is a repeat right now for:
- hard-coded array lengths that may not match
- off by one array index management, either treating 1 as first or missing last.

I didn't want to pull too much more threads before the sweater is a ball of yarn on this PR.

2024-10-20 14:57 UTC, jhillacre commented
@OH296 thanks for the review & suggestions.

`armour_data` doesn't appear to be on my branch at the moment, but `get_armour_data` does. Is `[EttyKitty:compile/main](https://github.com/EttyKitty/ChapterMaster/tree/compile/main)` what a PR should be based on?

2024-10-20 15:26 UTC, EttyKitty commented
> `armour_data` doesn't appear to be on my branch at the moment, but `get_armour_data` does.

I assume that's just a typo. he probably meant get_armour_data().
armour_data doesn't seem to exist even on the other branches.


> Is [EttyKitty:compile/main](https://github.com/EttyKitty/ChapterMaster/tree/compile/main?rgh-link-date=2024-10-20T14%3A57%3A05Z) what a PR should be based on?

probably, yeah. the other active branch is for unit_draw changes, so probably unrelated to this pr.

2024-10-20 15:49 UTC, jhillacre commented
I was able to get in-game, and deal with orks, tyriands and traitors around and a starting area in both raids, attacks, and garrisons, with vehicles on the field.

I think this is ready.

2024-10-20 19:02 UTC, OH296 commented
> @OH296 thanks for the review & suggestions.
> 
> `armour_data` doesn't appear to be on my branch at the moment, but `get_armour_data` does. Is [EttyKitty:compile/main](https://github.com/EttyKitty/ChapterMaster/tree/compile/main) what a PR should be based on?

yes is as etty says so apologies for this, i was just working from github and didn't cross check across the code base

2024-10-20 19:03 UTC, OH296 commented on objects/obj_pnunit/Create_0.gml
> +// Hardcoded lengths lead to bounds issues when hardcoded values disagree.
> > any idea how many hard-coded values does this leave remaining?
> 
> I'd suspect anywhere there is a repeat right now for:
> 
> * hard-coded array lengths that may not match
> * off by one array index management, either treating 1 as first or missing last.
> 
> I didn't want to pull too many more threads before the sweater is a ball of yarn on this PR.

fully makes sense big pr's have a habit of making this code base go wonky

2024-10-20 19:26 UTC, OH296 approved these changes
aight gave a few tests and it seems to run fine, should be good @EttyKitty  i see no reason why this shouldn't go in the next compile which i'm thinking is going to be 0.9.4.0? it has quite a lot more going in it than a standard fix

2024-10-21 08:04 UTC, merged