Hireling fix 1
EttyKitty/ChapterMaster pull request #24
Opened 2024-10-24 14:01 UTC by Blogaugis

Added a "Combat Knife" to Skitarii soldiers;
Fixed Inquisition Crusader issue with gear item slot having an item belonging in a weapon group;
Added "Ork Armour" to "Ork Sniper";
Lots of TODO comments added;
Fixes the Crusaders not having Armour

2024-10-24 14:50 UTC, OH296 requested changes
I would suggest you familiarise yourself with the concept of OOP and the scr_marine_struct rather than focussing on scr_add_man its a poorly written file that we will probably not continue to expand and support

2024-10-24 14:50 UTC, OH296 commented on scripts/scr_add_man/scr_add_man.gml
> +			/* TODO - add the right faction stuff, and move the "switch (man_role) {" before uncommenting
we will not be making new additions using the scr_add_man script like this in the furture it's terrible practise, but these can stay commented for now as guidane

2024-10-24 14:50 UTC, OH296 commented on scripts/scr_add_man/scr_add_man.gml
> +	var non_marine_roles = ["Skitarii", "Techpriest", "Crusader", "Sister of Battle", "Sister Hospitaler", "Ranger", "Ork Sniper", "Flash Git"]; // if adding new hirelings, don't forget to update this l
this list will be irrelevant soon this is just retrospective of the old code base

2024-10-24 16:52 UTC, Blogaugis commented on scripts/scr_add_man/scr_add_man.gml
> +			/* TODO - add the right faction stuff, and move the "switch (man_role) {" before uncommenting
Ok, I'll try fiddling around with the scr_marine_struct in future PRs.

2024-10-24 16:53 UTC, Blogaugis commented on scripts/scr_add_man/scr_add_man.gml
> +	var non_marine_roles = ["Skitarii", "Techpriest", "Crusader", "Sister of Battle", "Sister Hospitaler", "Ranger", "Ork Sniper", "Flash Git"]; // if adding new hirelings, don't forget to update this l
Understood.

2024-11-04 22:08 UTC, EttyKitty reviewed
I think considering that https://github.com/EttyKitty/ChapterMaster/pull/27 already adds light power armour and light bolter, you may want to merge loadout bits of this PR into that PR instead, and close this one.

2024-11-05 08:56 UTC, Blogaugis commented
Understood, I'll try to merge it to #27 .

2024-11-05 09:08 UTC, Blogaugis commented
Done, it seems.

2024-11-05 09:08 UTC, closed without merging