Logging improvments, Build Date-Time, auto bumping with actions
EttyKitty/ChapterMaster pull request #57
Opened 2024-10-31 22:10 UTC by EttyKitty

2024-11-01 23:57 UTC, OH296 requested changes
one minor error, otherwise all seems good

2024-11-01 23:57 UTC, OH296 commented on scripts/scr_json_functions/scr_json_functions.gml
> +            while (!file_text_eof(_file)) {
i presume there is no way a text file could end up having lines being added making this an infinite loop? (always worth asking when it comes to while loops lol)

2024-11-01 23:57 UTC, OH296 commented on scripts/scr_log/scr_log.gml
> +    if (string_length(_message > 0)) {
```suggestion
    if (string_length(_message) > 0) {
```

2024-11-02 00:02 UTC, EttyKitty commented on scripts/scr_json_functions/scr_json_functions.gml
> +            while (!file_text_eof(_file)) {
@OH296,
I don't think so?
And I'm not sure if it's possible to failsafe this without an overhead. Especially if the input file will be big.

2024-11-02 00:02 UTC, EttyKitty commented on scripts/scr_log/scr_log.gml
> +    if (string_length(_message > 0)) {
@OH296,
is this an error?

2024-11-02 00:16 UTC, OH296 commented on scripts/scr_json_functions/scr_json_functions.gml
> +            while (!file_text_eof(_file)) {
not a big issue probably fine

2024-11-02 00:17 UTC, merged