feat: disable warp route jumping; change key combo; fix tooltip
EttyKitty/ChapterMaster pull request #62
Opened 2024-11-01 22:00 UTC by EttyKitty

- Disabled automatic warp route screen pan, as it was just obnoxious. Very often it was just sending your screen flying when you didn't need that.
- Changed manual pan trigger from just clicking to SHIFT+click, to prevent missclicks.
- Fixed tooltip flipping not working on the star map.

2024-11-01 23:50 UTC, OH296 requested changes
minor issue is there is now no way to travel to the end point of a lane while a fleet is selected as clicking with the left will destroy the obj fleet select which makes long distance  lanes essentially unusable as who can be assed to manually scroll across the map and find  a name

2024-11-01 23:54 UTC, EttyKitty commented
> as clicking with the left will destroy the obj fleet select

Well, that's not good. Let's see if I can do something.

2024-11-02 00:09 UTC, EttyKitty commented
@OH296, is it viable to just disable the fleet deselection on click if shift is held?

2024-11-02 00:14 UTC, OH296 commented
> @OH296, is it viable to just disable the fleet deselection on click if shift is held?

i think so, i know the code so i can sort a pr to here tomorrow

2024-11-02 00:26 UTC, EttyKitty commented
> i think so, i know the code so i can sort a pr to here tomorrow

Thanks. I'll leave this to you, as I can't quickly find where it happens.

2024-11-04 12:21 UTC, OH296 commented
Is the delay on merging this down to the tooltip disappearing? minor enough issue imo but if so i can look into it a bit later?

2024-11-04 18:20 UTC, EttyKitty commented
> Is the delay on merging this down to the tooltip disappearing? minor enough issue imo but if so i can look into it a bit later?

Well, tbh I would like to solve it before merge. It's a pretty minor error but very nasty imo.
But if it's a headache - I can merge this and we think of a fix later.

2024-11-04 18:37 UTC, OH296 commented
> > Is the delay on merging this down to the tooltip disappearing? minor enough issue imo but if so i can look into it a bit later?
> 
> Well, tbh I would like to solve it before merge. It's a pretty minor error but very nasty imo. But if it's a headache - I can merge this and we think of a fix later.

i don't know if it's tricky or not as yet but i have a nasty feeling it will be time consuming. leave it a few days but if it's not done soonish just merge would be my current position

2024-11-10 03:54 UTC, EttyKitty commented
Could it be that the tooltip fix was this easy? Was there a reason why you disallow drawing the tooltip with shift held?

2024-11-11 13:52 UTC, merged